{% set name = "pyngo" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyngo-{{ version }}.tar.gz
  sha256: e40c9f9b20d65669c015397ed1c7139206f75bbc2d388074903b142e106897a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - typing-extensions >=3.7.4,<4.5.0
    - pydantic >=1.8.2,<2.0.0
    - django >=3.2.0,<4.0.0

test:
  imports:
    - pyngo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yezz123/pyngo
  summary: Pydantic Package for Adding Models into a Django or Django Rest Framework Project
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
